// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net.NetworkInformation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace kvad_be.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250325105639_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChatMessage", b =>
                {
                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("uuid");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ChatRoomId", "Id");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("ChatRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ChatRooms");
                });

            modelBuilder.Entity("ChatRoomUser", b =>
                {
                    b.Property<Guid>("ChatRoomsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("ChatRoomsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("ChatRoomUser");
                });

            modelBuilder.Entity("Dashboard", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("scrollable")
                        .HasColumnType("boolean");

                    b.HasKey("Id", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Dashboards");
                });

            modelBuilder.Entity("DashboardItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("DashboardId")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<Guid?>("DashboardUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id", "DashboardId");

                    b.HasIndex("DashboardId", "DashboardUserId");

                    b.ToTable("DashboardItems");
                });

            modelBuilder.Entity("Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<PhysicalAddress>("Mac")
                        .IsRequired()
                        .HasColumnType("macaddr");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.Property<int>("GroupsId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("GroupsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("GroupUser");
                });

            modelBuilder.Entity("KeyValue", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("KeyValues");
                });

            modelBuilder.Entity("Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("observedContainers")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("observedServices")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Moderator"
                        },
                        new
                        {
                            Id = 3,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleUser");

                    b.HasData(
                        new
                        {
                            RolesId = 1,
                            UsersId = new Guid("cf960f59-cf1f-49cc-8b2c-de4c5e437730")
                        });
                });

            modelBuilder.Entity("SIPrefix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Factor")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UnitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("SIPrefixes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Factor = 9.9999999999999998E+23,
                            Name = "Yotta",
                            Symbol = "Y"
                        },
                        new
                        {
                            Id = 2,
                            Factor = 1E+21,
                            Name = "Zetta",
                            Symbol = "Z"
                        },
                        new
                        {
                            Id = 3,
                            Factor = 1E+18,
                            Name = "Exa",
                            Symbol = "E"
                        },
                        new
                        {
                            Id = 4,
                            Factor = 1000000000000000.0,
                            Name = "Peta",
                            Symbol = "P"
                        },
                        new
                        {
                            Id = 5,
                            Factor = 1000000000000.0,
                            Name = "Tera",
                            Symbol = "T"
                        },
                        new
                        {
                            Id = 6,
                            Factor = 1000000000.0,
                            Name = "Giga",
                            Symbol = "G"
                        },
                        new
                        {
                            Id = 7,
                            Factor = 1000000.0,
                            Name = "Mega",
                            Symbol = "M"
                        },
                        new
                        {
                            Id = 8,
                            Factor = 1000.0,
                            Name = "Kilo",
                            Symbol = "k"
                        },
                        new
                        {
                            Id = 9,
                            Factor = 100.0,
                            Name = "Hecto",
                            Symbol = "h"
                        },
                        new
                        {
                            Id = 10,
                            Factor = 10.0,
                            Name = "Deca",
                            Symbol = "da"
                        },
                        new
                        {
                            Id = 11,
                            Factor = 0.10000000000000001,
                            Name = "Deci",
                            Symbol = "d"
                        },
                        new
                        {
                            Id = 12,
                            Factor = 0.01,
                            Name = "Centi",
                            Symbol = "c"
                        },
                        new
                        {
                            Id = 13,
                            Factor = 0.001,
                            Name = "Milli",
                            Symbol = "m"
                        },
                        new
                        {
                            Id = 14,
                            Factor = 9.9999999999999995E-07,
                            Name = "Micro",
                            Symbol = "μ"
                        },
                        new
                        {
                            Id = 15,
                            Factor = 1.0000000000000001E-09,
                            Name = "Nano",
                            Symbol = "n"
                        },
                        new
                        {
                            Id = 16,
                            Factor = 9.9999999999999998E-13,
                            Name = "Pico",
                            Symbol = "p"
                        },
                        new
                        {
                            Id = 17,
                            Factor = 1.0000000000000001E-15,
                            Name = "Femto",
                            Symbol = "f"
                        },
                        new
                        {
                            Id = 18,
                            Factor = 1.0000000000000001E-18,
                            Name = "Atto",
                            Symbol = "a"
                        },
                        new
                        {
                            Id = 19,
                            Factor = 9.9999999999999991E-22,
                            Name = "Zepto",
                            Symbol = "z"
                        },
                        new
                        {
                            Id = 20,
                            Factor = 9.9999999999999992E-25,
                            Name = "Yocto",
                            Symbol = "y"
                        });
                });

            modelBuilder.Entity("Tag", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int?>("DashboardItemDashboardId")
                        .HasColumnType("integer");

                    b.Property<int?>("DashboardItemId")
                        .HasColumnType("integer");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.HasKey("DeviceId", "Id");

                    b.HasIndex("UnitId");

                    b.HasIndex("DashboardItemId", "DashboardItemDashboardId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseUnitRelation")
                        .HasColumnType("text");

                    b.Property<string>("Dimension")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Parameter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Prefixable")
                        .HasColumnType("boolean");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dimension = "L",
                            Name = "Meter",
                            Parameter = "Length",
                            Prefixable = true,
                            Symbol = "m",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Dimension = "M",
                            Name = "Kilogram",
                            Parameter = "Mass",
                            Prefixable = true,
                            Symbol = "kg",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Dimension = "T",
                            Name = "Second",
                            Parameter = "Time",
                            Prefixable = true,
                            Symbol = "s",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Dimension = "I",
                            Name = "Ampere",
                            Parameter = "Electric Current",
                            Prefixable = true,
                            Symbol = "A",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Dimension = "Θ",
                            Name = "Kelvin",
                            Parameter = "Temperature",
                            Prefixable = true,
                            Symbol = "K",
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Dimension = "N",
                            Name = "Mole",
                            Parameter = "Amount of Substance",
                            Prefixable = true,
                            Symbol = "mol",
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Dimension = "J",
                            Name = "Candela",
                            Parameter = "Luminous Intensity",
                            Prefixable = true,
                            Symbol = "cd",
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            Dimension = "T^-1",
                            Name = "Hertz",
                            Parameter = "Frequency",
                            Prefixable = true,
                            Symbol = "Hz",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Dimension = "M L T^-2",
                            Name = "Newton",
                            Parameter = "Force",
                            Prefixable = true,
                            Symbol = "N",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            Dimension = "M L^-1 T^-2",
                            Name = "Pascal",
                            Parameter = "Pressure",
                            Prefixable = true,
                            Symbol = "Pa",
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            Dimension = "M L^2 T^-2",
                            Name = "Joule",
                            Parameter = "Energy",
                            Prefixable = true,
                            Symbol = "J",
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            Dimension = "M L^2 T^-3",
                            Name = "Watt",
                            Parameter = "Power",
                            Prefixable = true,
                            Symbol = "W",
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            Dimension = "I T",
                            Name = "Coulomb",
                            Parameter = "Electric Charge",
                            Prefixable = true,
                            Symbol = "C",
                            Type = 1
                        },
                        new
                        {
                            Id = 14,
                            Dimension = "M L^2 T^-3 I^-1",
                            Name = "Volt",
                            Parameter = "Electric Potential",
                            Prefixable = true,
                            Symbol = "V",
                            Type = 1
                        },
                        new
                        {
                            Id = 15,
                            Dimension = "M^-1 L^-2 T^4 I^2",
                            Name = "Farad",
                            Parameter = "Capacitance",
                            Prefixable = true,
                            Symbol = "F",
                            Type = 1
                        },
                        new
                        {
                            Id = 16,
                            Dimension = "M L^2 T^-3 I^-2",
                            Name = "Ohm",
                            Parameter = "Resistance",
                            Prefixable = true,
                            Symbol = "Ω",
                            Type = 1
                        },
                        new
                        {
                            Id = 17,
                            Dimension = "M^-1 L^-2 T^3 I^2",
                            Name = "Siemens",
                            Parameter = "Conductance",
                            Prefixable = true,
                            Symbol = "S",
                            Type = 1
                        },
                        new
                        {
                            Id = 18,
                            Dimension = "M L^2 T^-2 I^-1",
                            Name = "Weber",
                            Parameter = "Magnetic Flux",
                            Prefixable = true,
                            Symbol = "Wb",
                            Type = 1
                        },
                        new
                        {
                            Id = 19,
                            Dimension = "M L^-1 T^-2 I^-1",
                            Name = "Tesla",
                            Parameter = "Magnetic Flux Density",
                            Prefixable = true,
                            Symbol = "T",
                            Type = 1
                        },
                        new
                        {
                            Id = 20,
                            Dimension = "M L^2 T^-2 I^-2",
                            Name = "Henry",
                            Parameter = "Inductance",
                            Prefixable = true,
                            Symbol = "H",
                            Type = 1
                        },
                        new
                        {
                            Id = 21,
                            Dimension = "J",
                            Name = "Lumen",
                            Parameter = "Luminous Flux",
                            Prefixable = true,
                            Symbol = "lm",
                            Type = 1
                        },
                        new
                        {
                            Id = 22,
                            Dimension = "J L^-2",
                            Name = "Lux",
                            Parameter = "Illuminance",
                            Prefixable = true,
                            Symbol = "lx",
                            Type = 1
                        },
                        new
                        {
                            Id = 23,
                            Dimension = "T^-1",
                            Name = "Becquerel",
                            Parameter = "Radioactivity",
                            Prefixable = true,
                            Symbol = "Bq",
                            Type = 1
                        },
                        new
                        {
                            Id = 24,
                            Dimension = "L^2 T^-2",
                            Name = "Gray",
                            Parameter = "Absorbed Dose",
                            Prefixable = true,
                            Symbol = "Gy",
                            Type = 1
                        },
                        new
                        {
                            Id = 25,
                            Dimension = "L^2 T^-2",
                            Name = "Sievert",
                            Parameter = "Equivalent Dose",
                            Prefixable = true,
                            Symbol = "Sv",
                            Type = 1
                        },
                        new
                        {
                            Id = 26,
                            Dimension = "N T^-1",
                            Name = "Katal",
                            Parameter = "Catalytic Activity",
                            Prefixable = true,
                            Symbol = "kat",
                            Type = 1
                        },
                        new
                        {
                            Id = 27,
                            Dimension = "M L^2 T^-3",
                            Name = "Apparent Power",
                            Parameter = "Apparent Power",
                            Prefixable = true,
                            Symbol = "VA",
                            Type = 1
                        },
                        new
                        {
                            Id = 28,
                            Dimension = "M L^2 T^-3",
                            Name = "Reactive Power",
                            Parameter = "Reactive Power",
                            Prefixable = true,
                            Symbol = "var",
                            Type = 1
                        },
                        new
                        {
                            Id = 29,
                            Dimension = "M L^2 T^-3",
                            Name = "Active Power",
                            Parameter = "Active Power",
                            Prefixable = true,
                            Symbol = "W",
                            Type = 1
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("Username");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cf960f59-cf1f-49cc-8b2c-de4c5e437730"),
                            Icon = "cf960f59-cf1f-49cc-8b2c-de4c5e437730.png",
                            Password = "$argon2id$v=19$m=32768,t=4,p=1$g8fJIqwvK69pwVZEFI2+NQ$X5P9Sd32U7UTUJmjFP/t6P5vW/7lNS/RQYLE3nPbvXU",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("ChatMessage", b =>
                {
                    b.HasOne("ChatRoom", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChatRoomUser", b =>
                {
                    b.HasOne("ChatRoom", null)
                        .WithMany()
                        .HasForeignKey("ChatRoomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dashboard", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DashboardItem", b =>
                {
                    b.HasOne("Dashboard", "Dashboard")
                        .WithMany()
                        .HasForeignKey("DashboardId", "DashboardUserId");

                    b.Navigation("Dashboard");
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.HasOne("Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIPrefix", b =>
                {
                    b.HasOne("Unit", null)
                        .WithMany("Prefix")
                        .HasForeignKey("UnitId");
                });

            modelBuilder.Entity("Tag", b =>
                {
                    b.HasOne("Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DashboardItem", null)
                        .WithMany("Tags")
                        .HasForeignKey("DashboardItemId", "DashboardItemDashboardId");

                    b.Navigation("Device");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ChatRoom", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("DashboardItem", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Unit", b =>
                {
                    b.Navigation("Prefix");
                });
#pragma warning restore 612, 618
        }
    }
}
