// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net.NetworkInformation;
using System.Text.Json.Nodes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace kvad_be.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChatMessage", b =>
                {
                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("uuid");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ChatRoomId", "Id");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("ChatRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ChatRooms");
                });

            modelBuilder.Entity("ChatRoomUser", b =>
                {
                    b.Property<Guid>("ChatRoomsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("ChatRoomsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("ChatRoomUser");
                });

            modelBuilder.Entity("Dashboard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("DashboardTypeId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Scrollable")
                        .HasColumnType("boolean");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DashboardTypeId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Dashboards");
                });

            modelBuilder.Entity("DashboardGroup", b =>
                {
                    b.Property<Guid>("DashboardsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupsId")
                        .HasColumnType("uuid");

                    b.HasKey("DashboardsId", "GroupsId");

                    b.HasIndex("GroupsId");

                    b.ToTable("DashboardGroup");
                });

            modelBuilder.Entity("DashboardType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VueComponent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DashboardTypes");

                    b.HasData(
                        new
                        {
                            Id = "custom",
                            Description = "Custom dashboard type",
                            Name = "Custom",
                            VueComponent = "CustomDashboard.vue"
                        },
                        new
                        {
                            Id = "masonry",
                            Description = "Masonry dashboard type",
                            Name = "Masonry",
                            VueComponent = "MasonryDashboard.vue"
                        },
                        new
                        {
                            Id = "grid",
                            Description = "Grid dashboard type",
                            Name = "Grid",
                            VueComponent = "GridDashboard.vue"
                        },
                        new
                        {
                            Id = "scada",
                            Description = "Scada dashboard type",
                            Name = "Scada",
                            VueComponent = "ScadaDashboard.vue"
                        });
                });

            modelBuilder.Entity("Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<PhysicalAddress>("Mac")
                        .HasColumnType("macaddr");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Virtual")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("DeviceGroup", b =>
                {
                    b.Property<Guid>("DevicesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupsId")
                        .HasColumnType("uuid");

                    b.HasKey("DevicesId", "GroupsId");

                    b.HasIndex("GroupsId");

                    b.ToTable("DeviceGroup");
                });

            modelBuilder.Entity("DeviceState", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Connected")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Online")
                        .HasColumnType("boolean");

                    b.HasKey("DeviceId");

                    b.ToTable("DeviceState");
                });

            modelBuilder.Entity("Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.Property<Guid>("GroupsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("GroupsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("GroupUser");
                });

            modelBuilder.Entity("KeyValue", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("KeyValues");
                });

            modelBuilder.Entity("Layout", b =>
                {
                    b.Property<Guid>("DashboardId")
                        .HasColumnType("uuid");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<string>("Height")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentDashboardId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WidgetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Width")
                        .HasColumnType("text");

                    b.HasKey("DashboardId", "Id");

                    b.HasIndex("DashboardId")
                        .IsUnique();

                    b.HasIndex("WidgetId");

                    b.HasIndex("ParentDashboardId", "ParentId");

                    b.ToTable("Layouts");
                });

            modelBuilder.Entity("Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("observedContainers")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("observedServices")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Moderator"
                        },
                        new
                        {
                            Id = 3,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("SIPrefix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Factor")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UnitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("SIPrefixes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Factor = 9.9999999999999998E+23,
                            Name = "Yotta",
                            Symbol = "Y"
                        },
                        new
                        {
                            Id = 2,
                            Factor = 1E+21,
                            Name = "Zetta",
                            Symbol = "Z"
                        },
                        new
                        {
                            Id = 3,
                            Factor = 1E+18,
                            Name = "Exa",
                            Symbol = "E"
                        },
                        new
                        {
                            Id = 4,
                            Factor = 1000000000000000.0,
                            Name = "Peta",
                            Symbol = "P"
                        },
                        new
                        {
                            Id = 5,
                            Factor = 1000000000000.0,
                            Name = "Tera",
                            Symbol = "T"
                        },
                        new
                        {
                            Id = 6,
                            Factor = 1000000000.0,
                            Name = "Giga",
                            Symbol = "G"
                        },
                        new
                        {
                            Id = 7,
                            Factor = 1000000.0,
                            Name = "Mega",
                            Symbol = "M"
                        },
                        new
                        {
                            Id = 8,
                            Factor = 1000.0,
                            Name = "Kilo",
                            Symbol = "k"
                        },
                        new
                        {
                            Id = 9,
                            Factor = 100.0,
                            Name = "Hecto",
                            Symbol = "h"
                        },
                        new
                        {
                            Id = 10,
                            Factor = 10.0,
                            Name = "Deca",
                            Symbol = "da"
                        },
                        new
                        {
                            Id = 11,
                            Factor = 0.10000000000000001,
                            Name = "Deci",
                            Symbol = "d"
                        },
                        new
                        {
                            Id = 12,
                            Factor = 0.01,
                            Name = "Centi",
                            Symbol = "c"
                        },
                        new
                        {
                            Id = 13,
                            Factor = 0.001,
                            Name = "Milli",
                            Symbol = "m"
                        },
                        new
                        {
                            Id = 14,
                            Factor = 9.9999999999999995E-07,
                            Name = "Micro",
                            Symbol = "μ"
                        },
                        new
                        {
                            Id = 15,
                            Factor = 1.0000000000000001E-09,
                            Name = "Nano",
                            Symbol = "n"
                        },
                        new
                        {
                            Id = 16,
                            Factor = 9.9999999999999998E-13,
                            Name = "Pico",
                            Symbol = "p"
                        },
                        new
                        {
                            Id = 17,
                            Factor = 1.0000000000000001E-15,
                            Name = "Femto",
                            Symbol = "f"
                        },
                        new
                        {
                            Id = 18,
                            Factor = 1.0000000000000001E-18,
                            Name = "Atto",
                            Symbol = "a"
                        },
                        new
                        {
                            Id = 19,
                            Factor = 9.9999999999999991E-22,
                            Name = "Zepto",
                            Symbol = "z"
                        },
                        new
                        {
                            Id = 20,
                            Factor = 9.9999999999999992E-25,
                            Name = "Yocto",
                            Symbol = "y"
                        });
                });

            modelBuilder.Entity("Tag", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("Historicize")
                        .HasColumnType("boolean");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.Property<bool>("Virtual")
                        .HasColumnType("boolean");

                    b.HasKey("DeviceId", "Id");

                    b.HasIndex("UnitId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("TagHist", b =>
                {
                    b.Property<Guid>("TagDeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("TagId")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonValue>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("TagDeviceId", "TagId", "Timestamp");

                    b.HasIndex("TagId", "Timestamp")
                        .IsDescending(false, true);

                    b.ToTable("TagHists");
                });

            modelBuilder.Entity("Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseUnitRelation")
                        .HasColumnType("text");

                    b.Property<string>("Dimension")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Parameter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Prefixable")
                        .HasColumnType("boolean");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dimension = "L",
                            Name = "Meter",
                            Parameter = "Length",
                            Prefixable = true,
                            Symbol = "m",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Dimension = "M",
                            Name = "Kilogram",
                            Parameter = "Mass",
                            Prefixable = true,
                            Symbol = "kg",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Dimension = "T",
                            Name = "Second",
                            Parameter = "Time",
                            Prefixable = true,
                            Symbol = "s",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Dimension = "I",
                            Name = "Ampere",
                            Parameter = "Electric Current",
                            Prefixable = true,
                            Symbol = "A",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Dimension = "Θ",
                            Name = "Kelvin",
                            Parameter = "Temperature",
                            Prefixable = true,
                            Symbol = "K",
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Dimension = "N",
                            Name = "Mole",
                            Parameter = "Amount of Substance",
                            Prefixable = true,
                            Symbol = "mol",
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Dimension = "J",
                            Name = "Candela",
                            Parameter = "Luminous Intensity",
                            Prefixable = true,
                            Symbol = "cd",
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            Dimension = "T^-1",
                            Name = "Hertz",
                            Parameter = "Frequency",
                            Prefixable = true,
                            Symbol = "Hz",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Dimension = "M L T^-2",
                            Name = "Newton",
                            Parameter = "Force",
                            Prefixable = true,
                            Symbol = "N",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            Dimension = "M L^-1 T^-2",
                            Name = "Pascal",
                            Parameter = "Pressure",
                            Prefixable = true,
                            Symbol = "Pa",
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            Dimension = "M L^2 T^-2",
                            Name = "Joule",
                            Parameter = "Energy",
                            Prefixable = true,
                            Symbol = "J",
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            Dimension = "M L^2 T^-3",
                            Name = "Watt",
                            Parameter = "Power",
                            Prefixable = true,
                            Symbol = "W",
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            Dimension = "I T",
                            Name = "Coulomb",
                            Parameter = "Electric Charge",
                            Prefixable = true,
                            Symbol = "C",
                            Type = 1
                        },
                        new
                        {
                            Id = 14,
                            Dimension = "M L^2 T^-3 I^-1",
                            Name = "Volt",
                            Parameter = "Electric Potential",
                            Prefixable = true,
                            Symbol = "V",
                            Type = 1
                        },
                        new
                        {
                            Id = 15,
                            Dimension = "M^-1 L^-2 T^4 I^2",
                            Name = "Farad",
                            Parameter = "Capacitance",
                            Prefixable = true,
                            Symbol = "F",
                            Type = 1
                        },
                        new
                        {
                            Id = 16,
                            Dimension = "M L^2 T^-3 I^-2",
                            Name = "Ohm",
                            Parameter = "Resistance",
                            Prefixable = true,
                            Symbol = "Ω",
                            Type = 1
                        },
                        new
                        {
                            Id = 17,
                            Dimension = "M^-1 L^-2 T^3 I^2",
                            Name = "Siemens",
                            Parameter = "Conductance",
                            Prefixable = true,
                            Symbol = "S",
                            Type = 1
                        },
                        new
                        {
                            Id = 18,
                            Dimension = "M L^2 T^-2 I^-1",
                            Name = "Weber",
                            Parameter = "Magnetic Flux",
                            Prefixable = true,
                            Symbol = "Wb",
                            Type = 1
                        },
                        new
                        {
                            Id = 19,
                            Dimension = "M L^-1 T^-2 I^-1",
                            Name = "Tesla",
                            Parameter = "Magnetic Flux Density",
                            Prefixable = true,
                            Symbol = "T",
                            Type = 1
                        },
                        new
                        {
                            Id = 20,
                            Dimension = "M L^2 T^-2 I^-2",
                            Name = "Henry",
                            Parameter = "Inductance",
                            Prefixable = true,
                            Symbol = "H",
                            Type = 1
                        },
                        new
                        {
                            Id = 21,
                            Dimension = "J",
                            Name = "Lumen",
                            Parameter = "Luminous Flux",
                            Prefixable = true,
                            Symbol = "lm",
                            Type = 1
                        },
                        new
                        {
                            Id = 22,
                            Dimension = "J L^-2",
                            Name = "Lux",
                            Parameter = "Illuminance",
                            Prefixable = true,
                            Symbol = "lx",
                            Type = 1
                        },
                        new
                        {
                            Id = 23,
                            Dimension = "T^-1",
                            Name = "Becquerel",
                            Parameter = "Radioactivity",
                            Prefixable = true,
                            Symbol = "Bq",
                            Type = 1
                        },
                        new
                        {
                            Id = 24,
                            Dimension = "L^2 T^-2",
                            Name = "Gray",
                            Parameter = "Absorbed Dose",
                            Prefixable = true,
                            Symbol = "Gy",
                            Type = 1
                        },
                        new
                        {
                            Id = 25,
                            Dimension = "L^2 T^-2",
                            Name = "Sievert",
                            Parameter = "Equivalent Dose",
                            Prefixable = true,
                            Symbol = "Sv",
                            Type = 1
                        },
                        new
                        {
                            Id = 26,
                            Dimension = "N T^-1",
                            Name = "Katal",
                            Parameter = "Catalytic Activity",
                            Prefixable = true,
                            Symbol = "kat",
                            Type = 1
                        },
                        new
                        {
                            Id = 27,
                            Dimension = "M L^2 T^-3",
                            Name = "Apparent Power",
                            Parameter = "Apparent Power",
                            Prefixable = true,
                            Symbol = "VA",
                            Type = 1
                        },
                        new
                        {
                            Id = 28,
                            Dimension = "M L^2 T^-3",
                            Name = "Reactive Power",
                            Parameter = "Reactive Power",
                            Prefixable = true,
                            Symbol = "var",
                            Type = 1
                        },
                        new
                        {
                            Id = 29,
                            Dimension = "M L^2 T^-3",
                            Name = "Active Power",
                            Parameter = "Active Power",
                            Prefixable = true,
                            Symbol = "W",
                            Type = 1
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PrivateGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("Username");

                    b.HasIndex("PrivateGroupId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Widget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("DashboardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DashboardId");

                    b.HasIndex("TypeId");

                    b.ToTable("Widgets");
                });

            modelBuilder.Entity("WidgetType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VueComponent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WidgetTypes");
                });

            modelBuilder.Entity("ChatMessage", b =>
                {
                    b.HasOne("ChatRoom", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChatRoomUser", b =>
                {
                    b.HasOne("ChatRoom", null)
                        .WithMany()
                        .HasForeignKey("ChatRoomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dashboard", b =>
                {
                    b.HasOne("DashboardType", "DashboardType")
                        .WithMany()
                        .HasForeignKey("DashboardTypeId");

                    b.HasOne("User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DashboardType");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DashboardGroup", b =>
                {
                    b.HasOne("Dashboard", null)
                        .WithMany()
                        .HasForeignKey("DashboardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Device", b =>
                {
                    b.HasOne("User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DeviceGroup", b =>
                {
                    b.HasOne("Device", null)
                        .WithMany()
                        .HasForeignKey("DevicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeviceState", b =>
                {
                    b.HasOne("Device", null)
                        .WithOne("State")
                        .HasForeignKey("DeviceState", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.HasOne("Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Layout", b =>
                {
                    b.HasOne("Dashboard", "Dashboard")
                        .WithOne("Layout")
                        .HasForeignKey("Layout", "DashboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Widget", "Widget")
                        .WithMany()
                        .HasForeignKey("WidgetId");

                    b.HasOne("Layout", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentDashboardId", "ParentId");

                    b.Navigation("Dashboard");

                    b.Navigation("Parent");

                    b.Navigation("Widget");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIPrefix", b =>
                {
                    b.HasOne("Unit", null)
                        .WithMany("Prefix")
                        .HasForeignKey("UnitId");
                });

            modelBuilder.Entity("Tag", b =>
                {
                    b.HasOne("Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("TagHist", b =>
                {
                    b.HasOne("Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagDeviceId", "TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasOne("Group", "PrivateGroup")
                        .WithOne("PrivateOwner")
                        .HasForeignKey("User", "PrivateGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrivateGroup");
                });

            modelBuilder.Entity("Widget", b =>
                {
                    b.HasOne("Dashboard", null)
                        .WithMany("Widgets")
                        .HasForeignKey("DashboardId");

                    b.HasOne("WidgetType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ChatRoom", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Dashboard", b =>
                {
                    b.Navigation("Layout");

                    b.Navigation("Widgets");
                });

            modelBuilder.Entity("Device", b =>
                {
                    b.Navigation("State")
                        .IsRequired();
                });

            modelBuilder.Entity("Group", b =>
                {
                    b.Navigation("PrivateOwner");
                });

            modelBuilder.Entity("Layout", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Unit", b =>
                {
                    b.Navigation("Prefix");
                });
#pragma warning restore 612, 618
        }
    }
}
