// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net.NetworkInformation;
using System.Text.Json;
using System.Text.Json.Nodes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace kvad_be.Extensions.PostgresComposite
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250902001102_TestCompositeTypes")]
    partial class TestCompositeTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChatMessage", b =>
                {
                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("uuid");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ChatRoomId", "Id");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("ChatRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ChatRooms");
                });

            modelBuilder.Entity("ChatRoomUser", b =>
                {
                    b.Property<Guid>("ChatRoomsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("ChatRoomsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("ChatRoomUser");
                });

            modelBuilder.Entity("Dashboard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("DashboardTypeId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Scrollable")
                        .HasColumnType("boolean");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DashboardTypeId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Dashboards");
                });

            modelBuilder.Entity("DashboardGroup", b =>
                {
                    b.Property<Guid>("DashboardsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupsId")
                        .HasColumnType("uuid");

                    b.HasKey("DashboardsId", "GroupsId");

                    b.HasIndex("GroupsId");

                    b.ToTable("DashboardGroup");
                });

            modelBuilder.Entity("DashboardType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VueComponent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DashboardTypes");

                    b.HasData(
                        new
                        {
                            Id = "custom",
                            Description = "Custom dashboard type",
                            Name = "Custom",
                            VueComponent = "CustomDashboard.vue"
                        },
                        new
                        {
                            Id = "masonry",
                            Description = "Masonry dashboard type",
                            Name = "Masonry",
                            VueComponent = "MasonryDashboard.vue"
                        },
                        new
                        {
                            Id = "grid",
                            Description = "Grid dashboard type",
                            Name = "Grid",
                            VueComponent = "GridDashboard.vue"
                        },
                        new
                        {
                            Id = "scada",
                            Description = "Scada dashboard type",
                            Name = "Scada",
                            VueComponent = "ScadaDashboard.vue"
                        });
                });

            modelBuilder.Entity("Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<PhysicalAddress>("Mac")
                        .HasColumnType("macaddr");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Virtual")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("DeviceGroup", b =>
                {
                    b.Property<Guid>("DevicesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupsId")
                        .HasColumnType("uuid");

                    b.HasKey("DevicesId", "GroupsId");

                    b.HasIndex("GroupsId");

                    b.ToTable("DeviceGroup");
                });

            modelBuilder.Entity("DeviceState", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Connected")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Online")
                        .HasColumnType("boolean");

                    b.HasKey("DeviceId");

                    b.ToTable("DeviceState");
                });

            modelBuilder.Entity("Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.Property<Guid>("GroupsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("GroupsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("GroupUser");
                });

            modelBuilder.Entity("HistorizationInterval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CronExpression")
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("Interval")
                        .HasColumnType("interval");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HistorizationIntervals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Immediate"
                        },
                        new
                        {
                            Id = 2,
                            Interval = new TimeSpan(0, 0, 0, 1, 0),
                            Name = "1s"
                        },
                        new
                        {
                            Id = 3,
                            Interval = new TimeSpan(0, 0, 0, 10, 0),
                            Name = "10s"
                        },
                        new
                        {
                            Id = 4,
                            Interval = new TimeSpan(0, 0, 1, 0, 0),
                            Name = "1m"
                        },
                        new
                        {
                            Id = 5,
                            Interval = new TimeSpan(0, 0, 5, 0, 0),
                            Name = "5m"
                        },
                        new
                        {
                            Id = 6,
                            Interval = new TimeSpan(0, 0, 10, 0, 0),
                            Name = "10m"
                        },
                        new
                        {
                            Id = 7,
                            Interval = new TimeSpan(0, 0, 15, 0, 0),
                            Name = "15m"
                        },
                        new
                        {
                            Id = 8,
                            Interval = new TimeSpan(0, 0, 30, 0, 0),
                            Name = "30m"
                        },
                        new
                        {
                            Id = 9,
                            Interval = new TimeSpan(0, 1, 0, 0, 0),
                            Name = "1h"
                        },
                        new
                        {
                            Id = 10,
                            Interval = new TimeSpan(0, 6, 0, 0, 0),
                            Name = "6h"
                        },
                        new
                        {
                            Id = 11,
                            Interval = new TimeSpan(0, 12, 0, 0, 0),
                            Name = "12h"
                        },
                        new
                        {
                            Id = 12,
                            Interval = new TimeSpan(1, 0, 0, 0, 0),
                            Name = "Daily"
                        },
                        new
                        {
                            Id = 13,
                            Interval = new TimeSpan(7, 0, 0, 0, 0),
                            Name = "Weekly"
                        });
                });

            modelBuilder.Entity("KeyValue", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("KeyValues");
                });

            modelBuilder.Entity("Layout", b =>
                {
                    b.Property<Guid>("DashboardId")
                        .HasColumnType("uuid");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<string>("Height")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentDashboardId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WidgetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Width")
                        .HasColumnType("text");

                    b.HasKey("DashboardId", "Id");

                    b.HasIndex("DashboardId")
                        .IsUnique();

                    b.HasIndex("WidgetId");

                    b.HasIndex("ParentDashboardId", "ParentId");

                    b.ToTable("Layouts");
                });

            modelBuilder.Entity("Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("observedContainers")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("observedServices")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Moderator"
                        },
                        new
                        {
                            Id = 3,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("ScadaObjectTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ScadaObjectTemplates");
                });

            modelBuilder.Entity("Tag", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Historize")
                        .HasColumnType("boolean");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer");

                    b.Property<int?>("UnitId")
                        .HasColumnType("integer");

                    b.Property<string>("UnitSymbol")
                        .HasColumnType("text");

                    b.HasKey("DeviceId", "Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("UnitSymbol");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("TagCurr", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("TagId")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonValue>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("DeviceId", "TagId");

                    b.ToTable("TagCurr");
                });

            modelBuilder.Entity("TagHist", b =>
                {
                    b.Property<Guid>("TagDeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("TagId")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonValue>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("TagDeviceId", "TagId", "Timestamp");

                    b.HasIndex("TagId", "Timestamp")
                        .IsDescending(false, true);

                    b.ToTable("TagHists");
                });

            modelBuilder.Entity("TagSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Virtual")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("TagSources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Constant",
                            Virtual = true
                        },
                        new
                        {
                            Id = 2,
                            Name = "Computed",
                            Virtual = true
                        },
                        new
                        {
                            Id = 3,
                            Name = "MQTT",
                            Virtual = false
                        },
                        new
                        {
                            Id = 4,
                            Name = "Modbus",
                            Virtual = false
                        },
                        new
                        {
                            Id = 5,
                            Name = "OPC UA",
                            Virtual = false
                        },
                        new
                        {
                            Id = 6,
                            Name = "HTTP",
                            Virtual = false
                        },
                        new
                        {
                            Id = 7,
                            Name = "WebSocket",
                            Virtual = false
                        });
                });

            modelBuilder.Entity("Unit", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.Property<string>("Definition")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Prefixable")
                        .HasColumnType("boolean");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnitKind")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Symbol");

                    b.ToTable("Units");

                    b.HasDiscriminator<string>("UnitKind").HasValue("Unit");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("UnitCanonicalPart", b =>
                {
                    b.Property<string>("UnitSymbol")
                        .HasColumnType("text");

                    b.Property<string>("PartSymbol")
                        .HasColumnType("text");

                    b.HasKey("UnitSymbol", "PartSymbol");

                    b.HasIndex("PartSymbol");

                    b.ToTable("UnitCanonicalPart");
                });

            modelBuilder.Entity("UnitPrefix", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.Property<short>("Base")
                        .HasColumnType("smallint");

                    b.Property<short>("Exponent")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Symbol");

                    b.ToTable("Prefixes");

                    b.HasData(
                        new
                        {
                            Symbol = "Q",
                            Base = (short)10,
                            Exponent = (short)30,
                            Name = "Quetta"
                        },
                        new
                        {
                            Symbol = "R",
                            Base = (short)10,
                            Exponent = (short)27,
                            Name = "Ronna"
                        },
                        new
                        {
                            Symbol = "Y",
                            Base = (short)10,
                            Exponent = (short)24,
                            Name = "Yotta"
                        },
                        new
                        {
                            Symbol = "Z",
                            Base = (short)10,
                            Exponent = (short)21,
                            Name = "Zetta"
                        },
                        new
                        {
                            Symbol = "E",
                            Base = (short)10,
                            Exponent = (short)18,
                            Name = "Exa"
                        },
                        new
                        {
                            Symbol = "P",
                            Base = (short)10,
                            Exponent = (short)15,
                            Name = "Peta"
                        },
                        new
                        {
                            Symbol = "T",
                            Base = (short)10,
                            Exponent = (short)12,
                            Name = "Tera"
                        },
                        new
                        {
                            Symbol = "G",
                            Base = (short)10,
                            Exponent = (short)9,
                            Name = "Giga"
                        },
                        new
                        {
                            Symbol = "M",
                            Base = (short)10,
                            Exponent = (short)6,
                            Name = "Mega"
                        },
                        new
                        {
                            Symbol = "k",
                            Base = (short)10,
                            Exponent = (short)3,
                            Name = "Kilo"
                        },
                        new
                        {
                            Symbol = "h",
                            Base = (short)10,
                            Exponent = (short)2,
                            Name = "Hecto"
                        },
                        new
                        {
                            Symbol = "da",
                            Base = (short)10,
                            Exponent = (short)1,
                            Name = "Deca"
                        },
                        new
                        {
                            Symbol = "d",
                            Base = (short)10,
                            Exponent = (short)-1,
                            Name = "Deci"
                        },
                        new
                        {
                            Symbol = "c",
                            Base = (short)10,
                            Exponent = (short)-2,
                            Name = "Centi"
                        },
                        new
                        {
                            Symbol = "m",
                            Base = (short)10,
                            Exponent = (short)-3,
                            Name = "Milli"
                        },
                        new
                        {
                            Symbol = "μ",
                            Base = (short)10,
                            Exponent = (short)-6,
                            Name = "Micro"
                        },
                        new
                        {
                            Symbol = "n",
                            Base = (short)10,
                            Exponent = (short)-9,
                            Name = "Nano"
                        },
                        new
                        {
                            Symbol = "p",
                            Base = (short)10,
                            Exponent = (short)-12,
                            Name = "Pico"
                        },
                        new
                        {
                            Symbol = "f",
                            Base = (short)10,
                            Exponent = (short)-15,
                            Name = "Femto"
                        },
                        new
                        {
                            Symbol = "a",
                            Base = (short)10,
                            Exponent = (short)-18,
                            Name = "Atto"
                        },
                        new
                        {
                            Symbol = "z",
                            Base = (short)10,
                            Exponent = (short)-21,
                            Name = "Zepto"
                        },
                        new
                        {
                            Symbol = "y",
                            Base = (short)10,
                            Exponent = (short)-24,
                            Name = "Yocto"
                        },
                        new
                        {
                            Symbol = "r",
                            Base = (short)10,
                            Exponent = (short)-27,
                            Name = "Ronto"
                        },
                        new
                        {
                            Symbol = "q",
                            Base = (short)10,
                            Exponent = (short)-30,
                            Name = "Quecto"
                        },
                        new
                        {
                            Symbol = "Ki",
                            Base = (short)2,
                            Exponent = (short)10,
                            Name = "Kibi"
                        },
                        new
                        {
                            Symbol = "Mi",
                            Base = (short)2,
                            Exponent = (short)20,
                            Name = "Mebi"
                        },
                        new
                        {
                            Symbol = "Gi",
                            Base = (short)2,
                            Exponent = (short)30,
                            Name = "Gibi"
                        },
                        new
                        {
                            Symbol = "Ti",
                            Base = (short)2,
                            Exponent = (short)40,
                            Name = "Tebi"
                        },
                        new
                        {
                            Symbol = "Pi",
                            Base = (short)2,
                            Exponent = (short)50,
                            Name = "Pebi"
                        },
                        new
                        {
                            Symbol = "Ei",
                            Base = (short)2,
                            Exponent = (short)60,
                            Name = "Exbi"
                        },
                        new
                        {
                            Symbol = "Zi",
                            Base = (short)2,
                            Exponent = (short)70,
                            Name = "Zebi"
                        },
                        new
                        {
                            Symbol = "Yi",
                            Base = (short)2,
                            Exponent = (short)80,
                            Name = "Yobi"
                        },
                        new
                        {
                            Symbol = "Ri",
                            Base = (short)2,
                            Exponent = (short)90,
                            Name = "Roni"
                        },
                        new
                        {
                            Symbol = "Qi",
                            Base = (short)2,
                            Exponent = (short)100,
                            Name = "Quin"
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PrivateGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("Username");

                    b.HasIndex("PrivateGroupId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Widget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("DashboardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DashboardId");

                    b.HasIndex("TypeId");

                    b.ToTable("Widgets");
                });

            modelBuilder.Entity("WidgetType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VueComponent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WidgetTypes");
                });

            modelBuilder.Entity("AffineUnit", b =>
                {
                    b.HasBaseType("Unit");

                    b.Property<decimal>("Offset")
                        .HasColumnType("numeric");

                    b.HasDiscriminator().HasValue("affine");
                });

            modelBuilder.Entity("LinearUnit", b =>
                {
                    b.HasBaseType("Unit");

                    b.HasDiscriminator().HasValue("linear");

                    b.HasData(
                        new
                        {
                            Symbol = "m",
                            Name = "Meter",
                            Prefixable = true,
                            Quantity = "Length"
                        },
                        new
                        {
                            Symbol = "kg",
                            Name = "Kilogram",
                            Prefixable = true,
                            Quantity = "Mass"
                        },
                        new
                        {
                            Symbol = "s",
                            Name = "Second",
                            Prefixable = true,
                            Quantity = "Time"
                        },
                        new
                        {
                            Symbol = "A",
                            Name = "Ampere",
                            Prefixable = true,
                            Quantity = "Electric Current"
                        },
                        new
                        {
                            Symbol = "K",
                            Name = "Kelvin",
                            Prefixable = true,
                            Quantity = "Temperature"
                        },
                        new
                        {
                            Symbol = "mol",
                            Name = "Mole",
                            Prefixable = true,
                            Quantity = "Amount of Substance"
                        },
                        new
                        {
                            Symbol = "cd",
                            Name = "Candela",
                            Prefixable = true,
                            Quantity = "Luminous Intensity"
                        });
                });

            modelBuilder.Entity("LogarithmicUnit", b =>
                {
                    b.HasBaseType("Unit");

                    b.Property<string>("LogBase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("log");
                });

            modelBuilder.Entity("ChatMessage", b =>
                {
                    b.HasOne("ChatRoom", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChatRoomUser", b =>
                {
                    b.HasOne("ChatRoom", null)
                        .WithMany()
                        .HasForeignKey("ChatRoomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dashboard", b =>
                {
                    b.HasOne("DashboardType", "DashboardType")
                        .WithMany()
                        .HasForeignKey("DashboardTypeId");

                    b.HasOne("User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DashboardType");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DashboardGroup", b =>
                {
                    b.HasOne("Dashboard", null)
                        .WithMany()
                        .HasForeignKey("DashboardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Device", b =>
                {
                    b.HasOne("User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DeviceGroup", b =>
                {
                    b.HasOne("Device", null)
                        .WithMany()
                        .HasForeignKey("DevicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeviceState", b =>
                {
                    b.HasOne("Device", null)
                        .WithOne("State")
                        .HasForeignKey("DeviceState", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.HasOne("Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Layout", b =>
                {
                    b.HasOne("Dashboard", "Dashboard")
                        .WithOne("Layout")
                        .HasForeignKey("Layout", "DashboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Widget", "Widget")
                        .WithMany()
                        .HasForeignKey("WidgetId");

                    b.HasOne("Layout", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentDashboardId", "ParentId");

                    b.Navigation("Dashboard");

                    b.Navigation("Parent");

                    b.Navigation("Widget");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tag", b =>
                {
                    b.HasOne("Device", "Device")
                        .WithMany("Tags")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TagSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitSymbol");

                    b.Navigation("Device");

                    b.Navigation("Source");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("TagCurr", b =>
                {
                    b.HasOne("Tag", "Tag")
                        .WithOne("Curr")
                        .HasForeignKey("TagCurr", "DeviceId", "TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("TagHist", b =>
                {
                    b.HasOne("Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagDeviceId", "TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("UnitCanonicalPart", b =>
                {
                    b.HasOne("Unit", "Part")
                        .WithMany("PartOfUnits")
                        .HasForeignKey("PartSymbol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unit", "Unit")
                        .WithMany("CanonicalParts")
                        .HasForeignKey("UnitSymbol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasOne("Group", "PrivateGroup")
                        .WithOne("PrivateOwner")
                        .HasForeignKey("User", "PrivateGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrivateGroup");
                });

            modelBuilder.Entity("Widget", b =>
                {
                    b.HasOne("Dashboard", null)
                        .WithMany("Widgets")
                        .HasForeignKey("DashboardId");

                    b.HasOne("WidgetType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ChatRoom", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Dashboard", b =>
                {
                    b.Navigation("Layout");

                    b.Navigation("Widgets");
                });

            modelBuilder.Entity("Device", b =>
                {
                    b.Navigation("State")
                        .IsRequired();

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Group", b =>
                {
                    b.Navigation("PrivateOwner");
                });

            modelBuilder.Entity("Layout", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Tag", b =>
                {
                    b.Navigation("Curr")
                        .IsRequired();
                });

            modelBuilder.Entity("Unit", b =>
                {
                    b.Navigation("CanonicalParts");

                    b.Navigation("PartOfUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
