// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net.NetworkInformation;
using System.Text.Json;
using System.Text.Json.Nodes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using kvad_be.Database;

#nullable disable
[DbContext(typeof(AppDbContext))]
[Migration("20251120115627_DashboardHierarchy")]
partial class DashboardHierarchy
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "DeviceConnectivity", new[] { "online", "offline", "stale", "intermittent", "unreachable", "unknown" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "DeviceHealth", new[] { "healthy", "warning", "critical", "unknown" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "DeviceMode", new[] { "normal", "low_power", "sleep", "active", "idle", "maintenance", "emergency", "test", "unknown" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChatMessage", b =>
                {
                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("uuid");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ChatRoomId", "Id");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("ChatRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ChatRooms");
                });

            modelBuilder.Entity("ChatRoomUser", b =>
                {
                    b.Property<Guid>("ChatRoomsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("ChatRoomsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("ChatRoomUser");
                });

            modelBuilder.Entity("Dashboard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("DashboardTypeId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Scrollable")
                        .HasColumnType("boolean");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DashboardTypeId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Dashboards");
                });

            modelBuilder.Entity("DashboardGroup", b =>
                {
                    b.Property<Guid>("DashboardsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupsId")
                        .HasColumnType("uuid");

                    b.HasKey("DashboardsId", "GroupsId");

                    b.HasIndex("GroupsId");

                    b.ToTable("DashboardGroup");
                });

            modelBuilder.Entity("DashboardType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VueComponent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DashboardTypes");

                    b.HasData(
                        new
                        {
                            Id = "custom",
                            Description = "Custom dashboard type",
                            Name = "Custom",
                            VueComponent = "CustomDashboard.vue"
                        },
                        new
                        {
                            Id = "masonry",
                            Description = "Masonry dashboard type",
                            Name = "Masonry",
                            VueComponent = "MasonryDashboard.vue"
                        },
                        new
                        {
                            Id = "grid",
                            Description = "Grid dashboard type",
                            Name = "Grid",
                            VueComponent = "GridDashboard.vue"
                        },
                        new
                        {
                            Id = "scada",
                            Description = "Scada dashboard type",
                            Name = "Scada",
                            VueComponent = "ScadaDashboard.vue"
                        });
                });

            modelBuilder.Entity("Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Lifecycle")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<PhysicalAddress>("Mac")
                        .HasColumnType("macaddr");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Virtual")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "This is a virtual device for testing purposes.",
                            Lifecycle = 11,
                            Location = "Lab",
                            Name = "Virtual Device 1",
                            OwnerId = new Guid("cf960f59-cf1f-49cc-8b2c-de4c5e437730"),
                            Type = "Virtual",
                            Virtual = true
                        },
                        new
                        {
                            Id = new Guid("504b1696-2ad5-4109-ac28-5158965d6675"),
                            Description = "This is a physical test device.",
                            Lifecycle = 11,
                            Location = "Office",
                            Name = "Esp32 Test Device",
                            OwnerId = new Guid("cf960f59-cf1f-49cc-8b2c-de4c5e437730"),
                            Type = "Physical",
                            Virtual = false
                        });
                });

            modelBuilder.Entity("DeviceGroup", b =>
                {
                    b.Property<Guid>("DevicesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupsId")
                        .HasColumnType("uuid");

                    b.HasKey("DevicesId", "GroupsId");

                    b.HasIndex("GroupsId");

                    b.ToTable("DeviceGroup");
                });

            modelBuilder.Entity("DeviceInfo", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("Capabilities")
                        .HasColumnType("jsonb");

                    b.Property<string>("ConfigHash")
                        .HasColumnType("text");

                    b.Property<string>("Fw")
                        .HasColumnType("text");

                    b.Property<string>("Hw")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<JsonDocument>("Settings")
                        .HasColumnType("jsonb");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("DeviceId");

                    b.ToTable("DeviceInfo");

                    b.HasData(
                        new
                        {
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000001"),
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17265114000000000L)
                        });
                });

            modelBuilder.Entity("DeviceState", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("AdditionalHealth")
                        .HasColumnType("jsonb");

                    b.Property<string>("BootId")
                        .HasColumnType("text");

                    b.Property<string>("ConfigHash")
                        .HasColumnType("text");

                    b.Property<int>("Connectivity")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("Extra")
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("Flags")
                        .HasColumnType("jsonb");

                    b.Property<int?>("HbIntervalSec")
                        .HasColumnType("integer");

                    b.Property<short?>("HbJitterPct")
                        .HasColumnType("smallint");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<Instant?>("LastHeartbeat")
                        .HasColumnType("timestamptz");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<int?>("Rssi")
                        .HasColumnType("integer");

                    b.Property<long?>("Seq")
                        .HasColumnType("bigint");

                    b.Property<int?>("UptimeSec")
                        .HasColumnType("integer");

                    b.HasKey("DeviceId");

                    b.ToTable("DeviceState");

                    b.HasData(
                        new
                        {
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Connectivity = 5,
                            HbIntervalSec = 10,
                            HbJitterPct = (short)20,
                            Health = 3,
                            Mode = 8,
                            Seq = 0L,
                            UptimeSec = 0
                        });
                });

            modelBuilder.Entity("EnumUnitDimension", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("EnumUnitDimensions", t =>
                        {
                            t.HasTrigger("trg_enumunitdimension_expand_unit_dimensions");

                            t.HasTrigger("trg_enumunitdimension_prevent_delete_if_used");

                            t.HasTrigger("trg_enumunitdimension_validate_sequential_id");
                        });

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "Length",
                            Symbol = "L"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Mass",
                            Symbol = "M"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Time",
                            Symbol = "T"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Electric Current",
                            Symbol = "I"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Thermodynamic Temperature",
                            Symbol = "Θ"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Amount of Substance",
                            Symbol = "N"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Luminous Intensity",
                            Symbol = "J"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Angle",
                            Symbol = "A"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Currency",
                            Symbol = "C"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Information",
                            Symbol = "Sh"
                        });
                });

            modelBuilder.Entity("Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cf960f59-cf1f-49cc-8b2c-de4c5e437730"),
                            Name = "admin"
                        });
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.Property<Guid>("GroupsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("GroupsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("GroupUser");

                    b.HasData(
                        new
                        {
                            GroupsId = new Guid("cf960f59-cf1f-49cc-8b2c-de4c5e437730"),
                            UsersId = new Guid("cf960f59-cf1f-49cc-8b2c-de4c5e437730")
                        });
                });

            modelBuilder.Entity("KeyValue", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("KeyValues");
                });

            modelBuilder.Entity("Layout", b =>
                {
                    b.Property<Guid>("DashboardId")
                        .HasColumnType("uuid");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<string>("Height")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentDashboardId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WidgetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Width")
                        .HasColumnType("text");

                    b.HasKey("DashboardId", "Id");

                    b.HasIndex("DashboardId")
                        .IsUnique();

                    b.HasIndex("WidgetId");

                    b.HasIndex("ParentDashboardId", "ParentId");

                    b.ToTable("Layouts");
                });

            modelBuilder.Entity("Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("observedContainers")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("observedServices")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Moderator"
                        },
                        new
                        {
                            Id = 3,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleUser");

                    b.HasData(
                        new
                        {
                            RolesId = 1,
                            UsersId = new Guid("cf960f59-cf1f-49cc-8b2c-de4c5e437730")
                        });
                });

            modelBuilder.Entity("ScadaObjectTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ScadaObjectTemplates");
                });

            modelBuilder.Entity("Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<byte>("IO")
                        .HasColumnType("smallint");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short?>("Scale")
                        .HasColumnType("smallint");

                    b.Property<int?>("UnitId")
                        .HasColumnType("integer");

                    b.Property<int>("ValueKind")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Path")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("TagCurr", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.Property<double?>("Delta")
                        .HasColumnType("double precision");

                    b.Property<short>("Quality")
                        .HasColumnType("smallint");

                    b.Property<Instant>("Timestamp")
                        .HasColumnType("timestamptz");

                    b.Property<JsonDocument>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("TagId");

                    b.ToTable("TagCurr");
                });

            modelBuilder.Entity("TagHist", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.Property<Instant>("Ts")
                        .HasColumnType("timestamptz");

                    b.Property<short>("Quality")
                        .HasColumnType("smallint");

                    b.Property<bool?>("V_bool")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("V_bytea")
                        .HasColumnType("bytea");

                    b.Property<decimal?>("V_decimal")
                        .HasColumnType("decimal(38, 10)");

                    b.Property<short?>("V_enum")
                        .HasColumnType("smallint");

                    b.Property<double?>("V_f64")
                        .HasColumnType("double precision");

                    b.Property<long?>("V_i64")
                        .HasColumnType("bigint");

                    b.Property<JsonObject>("V_json")
                        .HasColumnType("jsonb");

                    b.Property<string>("V_string")
                        .HasColumnType("text");

                    b.HasKey("TagId", "Ts");

                    b.ToTable("TagHists", t =>
                        {
                            t.HasCheckConstraint("ck_hist_max_one_value", "((CASE WHEN \"V_decimal\" IS NOT NULL THEN 1 ELSE 0 END) +\n                (CASE WHEN \"V_f64\"    IS NOT NULL THEN 1 ELSE 0 END) +\n                (CASE WHEN \"V_i64\"    IS NOT NULL THEN 1 ELSE 0 END) +\n                (CASE WHEN \"V_enum\"   IS NOT NULL THEN 1 ELSE 0 END) +\n                (CASE WHEN \"V_bool\"   IS NOT NULL THEN 1 ELSE 0 END) +\n                (CASE WHEN \"V_string\" IS NOT NULL THEN 1 ELSE 0 END) +\n                (CASE WHEN \"V_json\"   IS NOT NULL THEN 1 ELSE 0 END) +\n                (CASE WHEN \"V_bytea\"  IS NOT NULL THEN 1 ELSE 0 END)) <= 1");
                        });
                });

            modelBuilder.Entity("TagHistPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AbsDeadband")
                        .HasColumnType("double precision");

                    b.Property<bool>("Aggregate")
                        .HasColumnType("boolean");

                    b.Property<int>("CaptureMode")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<double?>("PercentDeadband")
                        .HasColumnType("double precision");

                    b.Property<short?>("RoundDigits")
                        .HasColumnType("smallint");

                    b.Property<TimeSpan?>("SamplingInterval")
                        .HasColumnType("interval");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.Property<NpgsqlRange<DateTimeOffset>>("ValidRange")
                        .HasColumnType("tstzrange");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.ToTable("TagHistPolicy");
                });

            modelBuilder.Entity("TagSource", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("Config")
                        .HasColumnType("jsonb");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int>("Meta")
                        .HasColumnType("integer");

                    b.HasKey("TagId");

                    b.ToTable("TagSources");
                });

            modelBuilder.Entity("Unit", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.Property<string>("Definition")
                        .HasColumnType("text");

                    b.PrimitiveCollection<short[]>("Dimension")
                        .IsRequired()
                        .HasColumnType("smallint[]");

                    b.Property<long[]>("Factor")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Prefixable")
                        .HasColumnType("boolean");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnitKind")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Symbol");

                    b.ToTable("Units", t =>
                        {
                            t.HasTrigger("trg_unit_pad_dimension_array");
                        });

                    b.HasDiscriminator<string>("UnitKind").HasValue("Unit");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("UnitCanonicalPart", b =>
                {
                    b.Property<string>("UnitSymbol")
                        .HasColumnType("text");

                    b.Property<string>("PartSymbol")
                        .HasColumnType("text");

                    b.Property<long[]>("Exponent")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.HasKey("UnitSymbol", "PartSymbol");

                    b.HasIndex("PartSymbol");

                    b.ToTable("UnitCanonicalPart");
                });

            modelBuilder.Entity("UnitPrefix", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.Property<short>("Base")
                        .HasColumnType("smallint");

                    b.Property<short>("Exponent")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Symbol");

                    b.ToTable("Prefixes");

                    b.HasData(
                        new
                        {
                            Symbol = "Q",
                            Base = (short)10,
                            Exponent = (short)30,
                            Name = "Quetta"
                        },
                        new
                        {
                            Symbol = "R",
                            Base = (short)10,
                            Exponent = (short)27,
                            Name = "Ronna"
                        },
                        new
                        {
                            Symbol = "Y",
                            Base = (short)10,
                            Exponent = (short)24,
                            Name = "Yotta"
                        },
                        new
                        {
                            Symbol = "Z",
                            Base = (short)10,
                            Exponent = (short)21,
                            Name = "Zetta"
                        },
                        new
                        {
                            Symbol = "E",
                            Base = (short)10,
                            Exponent = (short)18,
                            Name = "Exa"
                        },
                        new
                        {
                            Symbol = "P",
                            Base = (short)10,
                            Exponent = (short)15,
                            Name = "Peta"
                        },
                        new
                        {
                            Symbol = "T",
                            Base = (short)10,
                            Exponent = (short)12,
                            Name = "Tera"
                        },
                        new
                        {
                            Symbol = "G",
                            Base = (short)10,
                            Exponent = (short)9,
                            Name = "Giga"
                        },
                        new
                        {
                            Symbol = "M",
                            Base = (short)10,
                            Exponent = (short)6,
                            Name = "Mega"
                        },
                        new
                        {
                            Symbol = "k",
                            Base = (short)10,
                            Exponent = (short)3,
                            Name = "Kilo"
                        },
                        new
                        {
                            Symbol = "h",
                            Base = (short)10,
                            Exponent = (short)2,
                            Name = "Hecto"
                        },
                        new
                        {
                            Symbol = "da",
                            Base = (short)10,
                            Exponent = (short)1,
                            Name = "Deca"
                        },
                        new
                        {
                            Symbol = "d",
                            Base = (short)10,
                            Exponent = (short)-1,
                            Name = "Deci"
                        },
                        new
                        {
                            Symbol = "c",
                            Base = (short)10,
                            Exponent = (short)-2,
                            Name = "Centi"
                        },
                        new
                        {
                            Symbol = "m",
                            Base = (short)10,
                            Exponent = (short)-3,
                            Name = "Milli"
                        },
                        new
                        {
                            Symbol = "μ",
                            Base = (short)10,
                            Exponent = (short)-6,
                            Name = "Micro"
                        },
                        new
                        {
                            Symbol = "n",
                            Base = (short)10,
                            Exponent = (short)-9,
                            Name = "Nano"
                        },
                        new
                        {
                            Symbol = "p",
                            Base = (short)10,
                            Exponent = (short)-12,
                            Name = "Pico"
                        },
                        new
                        {
                            Symbol = "f",
                            Base = (short)10,
                            Exponent = (short)-15,
                            Name = "Femto"
                        },
                        new
                        {
                            Symbol = "a",
                            Base = (short)10,
                            Exponent = (short)-18,
                            Name = "Atto"
                        },
                        new
                        {
                            Symbol = "z",
                            Base = (short)10,
                            Exponent = (short)-21,
                            Name = "Zepto"
                        },
                        new
                        {
                            Symbol = "y",
                            Base = (short)10,
                            Exponent = (short)-24,
                            Name = "Yocto"
                        },
                        new
                        {
                            Symbol = "r",
                            Base = (short)10,
                            Exponent = (short)-27,
                            Name = "Ronto"
                        },
                        new
                        {
                            Symbol = "q",
                            Base = (short)10,
                            Exponent = (short)-30,
                            Name = "Quecto"
                        },
                        new
                        {
                            Symbol = "Ki",
                            Base = (short)2,
                            Exponent = (short)10,
                            Name = "Kibi"
                        },
                        new
                        {
                            Symbol = "Mi",
                            Base = (short)2,
                            Exponent = (short)20,
                            Name = "Mebi"
                        },
                        new
                        {
                            Symbol = "Gi",
                            Base = (short)2,
                            Exponent = (short)30,
                            Name = "Gibi"
                        },
                        new
                        {
                            Symbol = "Ti",
                            Base = (short)2,
                            Exponent = (short)40,
                            Name = "Tebi"
                        },
                        new
                        {
                            Symbol = "Pi",
                            Base = (short)2,
                            Exponent = (short)50,
                            Name = "Pebi"
                        },
                        new
                        {
                            Symbol = "Ei",
                            Base = (short)2,
                            Exponent = (short)60,
                            Name = "Exbi"
                        },
                        new
                        {
                            Symbol = "Zi",
                            Base = (short)2,
                            Exponent = (short)70,
                            Name = "Zebi"
                        },
                        new
                        {
                            Symbol = "Yi",
                            Base = (short)2,
                            Exponent = (short)80,
                            Name = "Yobi"
                        },
                        new
                        {
                            Symbol = "Ri",
                            Base = (short)2,
                            Exponent = (short)90,
                            Name = "Roni"
                        },
                        new
                        {
                            Symbol = "Qi",
                            Base = (short)2,
                            Exponent = (short)100,
                            Name = "Quin"
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PrivateGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sidebar")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("Username");

                    b.HasIndex("PrivateGroupId")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cf960f59-cf1f-49cc-8b2c-de4c5e437730"),
                            Icon = "data/user_icons/cf960f59-cf1f-49cc-8b2c-de4c5e437730.png",
                            Password = "$argon2id$v=19$m=32768,t=4,p=1$g8fJIqwvK69pwVZEFI2+NQ$X5P9Sd32U7UTUJmjFP/t6P5vW/7lNS/RQYLE3nPbvXU",
                            PrivateGroupId = new Guid("cf960f59-cf1f-49cc-8b2c-de4c5e437730"),
                            Sidebar = "[]",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Widget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("DashboardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DashboardId");

                    b.HasIndex("TypeId");

                    b.ToTable("Widgets");
                });

            modelBuilder.Entity("WidgetType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VueComponent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WidgetTypes");
                });

            modelBuilder.Entity("AffineUnit", b =>
                {
                    b.HasBaseType("Unit");

                    b.Property<decimal>("Offset")
                        .HasColumnType("numeric");

                    b.HasDiscriminator().HasValue("affine");
                });

            modelBuilder.Entity("LinearUnit", b =>
                {
                    b.HasBaseType("Unit");

                    b.HasDiscriminator().HasValue("linear");

                    b.HasData(
                        new
                        {
                            Symbol = "m",
                            Dimension = new[] { (short)1, (short)0, (short)0, (short)0, (short)0, (short)0, (short)0 },
                            Factor = new[] { 1L, 1L },
                            Name = "Meter",
                            Prefixable = true,
                            Quantity = "Length"
                        },
                        new
                        {
                            Symbol = "kg",
                            Dimension = new[] { (short)0, (short)1, (short)0, (short)0, (short)0, (short)0, (short)0 },
                            Factor = new[] { 1L, 1L },
                            Name = "Kilogram",
                            Prefixable = true,
                            Quantity = "Mass"
                        },
                        new
                        {
                            Symbol = "s",
                            Dimension = new[] { (short)0, (short)0, (short)1, (short)0, (short)0, (short)0, (short)0 },
                            Factor = new[] { 1L, 1L },
                            Name = "Second",
                            Prefixable = true,
                            Quantity = "Time"
                        },
                        new
                        {
                            Symbol = "A",
                            Dimension = new[] { (short)0, (short)0, (short)0, (short)1, (short)0, (short)0, (short)0 },
                            Factor = new[] { 1L, 1L },
                            Name = "Ampere",
                            Prefixable = true,
                            Quantity = "Electric Current"
                        },
                        new
                        {
                            Symbol = "K",
                            Dimension = new[] { (short)0, (short)0, (short)0, (short)0, (short)1, (short)0, (short)0 },
                            Factor = new[] { 1L, 1L },
                            Name = "Kelvin",
                            Prefixable = true,
                            Quantity = "Temperature"
                        },
                        new
                        {
                            Symbol = "mol",
                            Dimension = new[] { (short)0, (short)0, (short)0, (short)0, (short)0, (short)1, (short)0 },
                            Factor = new[] { 1L, 1L },
                            Name = "Mole",
                            Prefixable = true,
                            Quantity = "Amount of Substance"
                        },
                        new
                        {
                            Symbol = "cd",
                            Dimension = new[] { (short)0, (short)0, (short)0, (short)0, (short)0, (short)0, (short)1 },
                            Factor = new[] { 1L, 1L },
                            Name = "Candela",
                            Prefixable = true,
                            Quantity = "Luminous Intensity"
                        });
                });

            modelBuilder.Entity("LogarithmicUnit", b =>
                {
                    b.HasBaseType("Unit");

                    b.Property<string>("LogBase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long[]>("LogK")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.Property<long[]>("LogRef")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.HasDiscriminator().HasValue("log");
                });

            modelBuilder.Entity("ChatMessage", b =>
                {
                    b.HasOne("ChatRoom", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChatRoomUser", b =>
                {
                    b.HasOne("ChatRoom", null)
                        .WithMany()
                        .HasForeignKey("ChatRoomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dashboard", b =>
                {
                    b.HasOne("DashboardType", "DashboardType")
                        .WithMany()
                        .HasForeignKey("DashboardTypeId");

                    b.HasOne("User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DashboardType");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DashboardGroup", b =>
                {
                    b.HasOne("Dashboard", null)
                        .WithMany()
                        .HasForeignKey("DashboardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Device", b =>
                {
                    b.HasOne("User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DeviceHeartbeatSettings", "HeartbeatSettings", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ExpectedInterval")
                                .HasColumnType("integer");

                            b1.Property<int>("HbIntervalThreshold")
                                .HasColumnType("integer");

                            b1.Property<int>("HbMissedThreshold")
                                .HasColumnType("integer");

                            b1.HasKey("DeviceId");

                            b1.ToTable("Devices");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.Navigation("HeartbeatSettings");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DeviceGroup", b =>
                {
                    b.HasOne("Device", null)
                        .WithMany()
                        .HasForeignKey("DevicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeviceInfo", b =>
                {
                    b.HasOne("Device", "Device")
                        .WithOne("Info")
                        .HasForeignKey("DeviceInfo", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("DeviceState", b =>
                {
                    b.HasOne("Device", "Device")
                        .WithOne("State")
                        .HasForeignKey("DeviceState", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.HasOne("Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Layout", b =>
                {
                    b.HasOne("Dashboard", "Dashboard")
                        .WithOne("Layout")
                        .HasForeignKey("Layout", "DashboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Widget", "Widget")
                        .WithMany()
                        .HasForeignKey("WidgetId");

                    b.HasOne("Layout", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentDashboardId", "ParentId");

                    b.Navigation("Dashboard");

                    b.Navigation("Parent");

                    b.Navigation("Widget");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tag", b =>
                {
                    b.HasOne("Device", "Device")
                        .WithMany("Tags")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("TagCurr", b =>
                {
                    b.HasOne("Tag", "Tag")
                        .WithOne("Curr")
                        .HasForeignKey("TagCurr", "TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("TagHistPolicy", b =>
                {
                    b.HasOne("Tag", null)
                        .WithMany("HistPolicies")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TagSource", b =>
                {
                    b.HasOne("Tag", "Tag")
                        .WithOne("Source")
                        .HasForeignKey("TagSource", "TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("UnitCanonicalPart", b =>
                {
                    b.HasOne("Unit", "Part")
                        .WithMany("PartOfUnits")
                        .HasForeignKey("PartSymbol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unit", "Unit")
                        .WithMany("CanonicalParts")
                        .HasForeignKey("UnitSymbol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasOne("Group", "PrivateGroup")
                        .WithOne("PrivateOwner")
                        .HasForeignKey("User", "PrivateGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrivateGroup");
                });

            modelBuilder.Entity("Widget", b =>
                {
                    b.HasOne("Dashboard", null)
                        .WithMany("Widgets")
                        .HasForeignKey("DashboardId");

                    b.HasOne("WidgetType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ChatRoom", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Dashboard", b =>
                {
                    b.Navigation("Layout");

                    b.Navigation("Widgets");
                });

            modelBuilder.Entity("Device", b =>
                {
                    b.Navigation("Info");

                    b.Navigation("State");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Group", b =>
                {
                    b.Navigation("PrivateOwner");
                });

            modelBuilder.Entity("Layout", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Tag", b =>
                {
                    b.Navigation("Curr")
                        .IsRequired();

                    b.Navigation("HistPolicies");

                    b.Navigation("Source")
                        .IsRequired();
                });

            modelBuilder.Entity("Unit", b =>
                {
                    b.Navigation("CanonicalParts");

                    b.Navigation("PartOfUnits");
                });
#pragma warning restore 612, 618
        }
    }
